### ISSUE TITLE
Connecting to the database fails for non-community database versions

### ISSUE THREAD

**Issue by chjahnert** [DarkWanderer/ClickHouse.Client#101]
We run the Altinity version of ClickHouse for which the database version string looks like `21.8.10.1.altinitystable`. When the client attempts to connect, we get an exception when we open the database connection.

```
System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at ClickHouse.Client.ADO.ClickHouseConnection.<OpenAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ClickHouse.Client.ADO.ClickHouseConnection.Open()
```
We use version 3.1.0.379 of the client.

**Comment by DarkWanderer** [comment]
Should be fixed in `4.1.0`
