### ISSUE TITLE
ParseVersion fails with Altinity Clickhouse

### ISSUE THREAD

**Issue by markatosi** [DarkWanderer/ClickHouse.Client#116]
The version of the server is: 21.8.13.1.altinitystable

I'm using 4.1.0 of your client.

I've tried connecting with another .Net client and it works as expected. Also all other database tools I have used (Datgrip, DBeaver)
connect and run commands correctly. 

System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at ClickHouse.Client.ADO.ClickHouseConnection.OpenAsync(CancellationToken token)
   at ClickHouse.Client.ADO.ClickHouseConnection.Open()

**Comment by markatosi** [comment]
I wasn't really using version 4.1.0 *sigh* this works fine now
