### ISSUE TITLE
Feature request: print row data on which bulk writer got exception

### ISSUE THREAD

**Issue by devzerker** [DarkWanderer/ClickHouse.Client#188]
Now when `WriteToServerAsync` method called and something is wrong with one of rows, for example, type mismatch, it raises generic exception like null ref
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClickHouse.Client.Types.ArrayType.Write(ExtendedBinaryWriter writer, Object value)
   at ClickHouse.Client.Copy.ClickHouseBulkCopy.PushBatch(ICollection`1 rows, ClickHouseType[] columnTypes, String[] columnNames, CancellationToken token)
   at ClickHouse.Client.Copy.ClickHouseBulkCopy.WriteToServerAsync(IEnumerable`1 rows, IReadOnlyCollection`1 columns, CancellationToken token)
```
And it hurts to find this row

**Comment by DarkWanderer** [comment]
5.1.0 now throws a richer exception which stores the data row involved. Does it cover your case?

**Comment by devzerker** [comment]
Yep, thx!
