### ISSUE TITLE
Unable to use without port

### ISSUE THREAD

**Issue by FreePhoenix888** [DarkWanderer/ClickHouse.Client#274]
Gitpod exposes its ports this way:
`https://8443-random-url.gitpod.io`
Therefore I have tried to write my connection string without port this way:
```
Host=8443-linksplatfo-doubletsvsc-dbgw0llbx05.ws-us88.gitpod.io;Protocol=https;Username=default;Password=123;Timeout=500
```
But it tried to use another port instead.
Error:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Net.Http.HttpRequestException: Connection timed out (8443-linksplatfo-doubletsvsc-dbgw0llbx05.ws-us88.gitpod.io:8123)
 ---> System.Net.Sockets.SocketException (110): Connection timed out
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   ```

**Comment by FreePhoenix888** [comment]
I had to set host to localhost
Host=localhost;Protocol=https;Port=8123;Username=default;Password=123;Timeout=500
