### ISSUE TITLE
Querying merge() table fails

### ISSUE THREAD

**Issue by fhmcn** [DarkWanderer/ClickHouse.Client#32]
Querying data from [merge()](https://clickhouse.tech/docs/en/engines/table-engines/special/merge/#merge) table engine does not work. 

```
Error : System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> ClickHouse.Client.ClickHouseServerException: Code: 16, e.displayText() = DB::Exception: There is no physical column _table in table. (version 20.3.8.53 (official build))

   at ClickHouse.Client.ADO.ClickHouseConnection.<HandleError>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ClickHouse.Client.ADO.ClickHouseConnection.<PostSqlQueryAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ClickHouse.Client.ADO.ClickHouseCommand.<ExecuteDbDataReaderAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ClickHouse.Client.ADO.ClickHouseCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
```

**Comment by fhmcn** [comment]
It appeared that issue is due to mismatch on merge table columns. Fixed by unifying column types.

**Comment by fhmcn** [comment]
It appeared that issue is due to mismatch on merge table columns. Fixed by unifying column types.
