### ISSUE TITLE
Exception (Version string portion was too short or too long) while sending request

### ISSUE THREAD

**Issue by DBalashov** [DarkWanderer/ClickHouse.Client#39]
Using last version Clickhouse.Client ( 2.0.0.262 ). Exception while processing request (.Query is Dapper extension, working fine with previous versions of Clickhouse.Client):

![20200702_220403](https://user-images.githubusercontent.com/2083946/86389636-0907e600-bcb0-11ea-9032-4270cca3ab4e.png)

`System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at ClickHouse.Client.Utility.FeatureDetectorExtensions.<SupportsHttpParameters>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ClickHouse.Client.ADO.ClickHouseConnection.<PostSqlQueryAsync>d__2

Connection string: Host=192.168.0.113;Port=8123;Database=AGNET;User=default;Password=P@ssw0rd
select version(): 20.5.2.7

**Comment by DBalashov** [comment]
solution in #38
