### ISSUE TITLE
Writing dates before 01.01.1970 

### ISSUE THREAD

**Issue by devTryer31** [DarkWanderer/ClickHouse.Client#407]
Hi
I am attempting to write `System.DateTime` with _07.10.1952_ date through `ClickHouseBulkCopy` class and got the exception:
```
System.OverflowException: Value was either too large or too small for a UInt16.
   at System.Convert.ThrowUInt16OverflowException()
   at System.Convert.ToUInt16(Double value)
   at ClickHouse.Client.Types.DateType.Write(ExtendedBinaryWriter writer, Object value)
   at ClickHouse.Client.Copy.ClickHouseBulkCopy.WriteToServerAsync(IEnumerable`1 rows, IReadOnlyCollection`1 columns, CancellationToken token)
``` 

I think it happened because I got negative total number of days due to subtraction with date 01.01.1970 (and got -6295 for example abow) here https://github.com/DarkWanderer/ClickHouse.Client/blob/e54814fe9598a211c3e294395e690fd6c3fd1900/ClickHouse.Client/Types/DateType.cs#L28

What do I need to do with dates less than 01.01.1970?

**Comment by devTryer31** [comment]
I needed to use the `Date32` column type.
