### ISSUE TITLE
BulkCopy not raising exception on big datasets

### ISSUE THREAD

**Issue by marcinatpayholdingcom** [DarkWanderer/ClickHouse.Client#475]
I was copying data from MSSQL to ClickHouse. My table was 2M rows. Each  time I was running the copy I was missing some rows. I was not getting any exception during the copy, everything was running nice and smooth (batch size 10k), but the data was missing, I reduced the data to 1k rows executed and this is what I got:

```
ClickHouse.Client.Copy.ClickHouseBulkCopySerializationException: Error when serializing data
 ---> System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt16(IFormatProvider provider)
   at ClickHouse.Client.Types.Int16Type.Write(ExtendedBinaryWriter writer, Object value)
   at ClickHouse.Client.Copy.ClickHouseBulkCopy.BulkCopyHttpContent.SerializeBatchAsync(Stream stream)
   --- End of inner exception stack trace ---
   at ClickHouse.Client.Copy.ClickHouseBulkCopy.BulkCopyHttpContent.SerializeBatchAsync(Stream stream)
   at ClickHouse.Client.Copy.ClickHouseBulkCopy.BulkCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at ClickHouse.Client.ADO.ClickHouseConnection.PostContentAsync(String sql, HttpContent httpData, CancellationToken token)
   at ClickHouse.Client.Copy.ClickHouseBulkCopy.SendBatchAsync(BulkCopyHttpContent batchContent, CancellationToken token)
   at ClickHouse.Client.Copy.ClickHouseBulkCopy.WriteToServerAsync(IEnumerable`1 rows, CancellationToken token)
   at DataSync.Data.Clients.Clickhouse.ChClient.<>c__DisplayClass4_0.<<BulkInsertAsync>b__0>d.MoveNext()
```

Which explained me what is the problem. Grate, but it took me a long time to realize that I have wrong column definition in CH. But the exception was not thrown on big data copy, it was just silent.

**Comment by DarkWanderer** [comment]
Hi
Thank you for your report, that would be a serious bug. Can you clarify a bit more on how this appeared - was the exception happening somewhere near the beginning of dataset or near the end?

Also, if you would be able to reproduce it - does the error reproduce on previous versions, e.g. 6.8.1?

**Comment by DarkWanderer** [comment]
I have tried to reproduce the issue in a test and it doesn't seem to appear with a synthetic test - a serialization exception is always correctly propagated. Can you provide more context please?

**Comment by marcinatpayholdingcom** [comment]
I will try to build demo for you.

On 9 May 2024, at 12:11, Oleg V. Kozlyuk ***@***.***> wrote:

﻿

I have tried to reproduce the issue in a test and it doesn't seem to appear with a synthetic test - a serialization exception is always correctly propagated. Can you provide more context please?

**Comment by DarkWanderer** [comment]
Please try version 7.5.0 to see if it fixes the issue for you

**Comment by marcinatpayholdingcom** [comment]
Nop, still not working correctly, here is a demo to replicate this problem. Let me know, maybe I am doing something wrong.
https://github.com/marcinatpayholdingcom/clickhouseclient_bug_replication

**Comment by marcinatpayholdingcom** [comment]
I am running this on Windows
this part should throw the serialization exception but it does not:
![image](https://github.com/DarkWanderer/ClickHouse.Client/assets/102699663/5ac9f145-fea9-4a6d-84eb-8c5e38ba1d65)

I do not have any special setting, I just run it as it is in the project.

**Comment by DarkWanderer** [comment]
For me it is triggered quite perfectly every time
![image](https://github.com/DarkWanderer/ClickHouse.Client/assets/2542609/0db97ceb-2aec-4b5c-ae43-5aa2c7331ae3)

Just to double check, when you say "exception is not thrown", have you checked it in the debugger by putting a breakpoint on the `logger._LogError` line, or did you chec only by looking at the logs? Because your test project does not output any logs even in case of error

**Comment by marcinatpayholdingcom** [comment]
by setting the brekpoin at the log line and by seeing what data got inserted into Clickhouse.
When you get the serialization exception that means that no data got inserted into Clickhouse in the first attempt, am I right?

In my case there is some data inserted.

**Comment by DarkWanderer** [comment]
I think there may be just a misunderstanding here, which means I'll need to make docs more clear

> When you get the serialization exception that means that no data got inserted into Clickhouse in the first attempt, am I right?

ClickHouse is not transactional (other than experimental features) - and hence BulkCopy adapter isn't as well. If you have a large set of data and the serialization (or insertion) has failed for one of the batches, it is expected that some of the batches may have made it through already, and it falls on the higher-level code to handles the situation. I.e. in this particular case, 20k of rows get into database before exception - and that's by design. 

If you need to have some semblance of atomicity, the data needs to go as one 'batch' - so you can try setting `BatchSize` to `Int32.MaxValue` ([reference](https://clickhouse.com/docs/en/guides/developer/transactional)). It would be slow and memory-consuming, but you would get a binary result.
