### ISSUE TITLE
[BUG] 7.9.0 throws an exception

### ISSUE THREAD

**Issue by igor-tkachev** [DarkWanderer/ClickHouse.Client#549]
### Current Behavior

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LinqToDB.LinqToDBException: Constructor not found in target type: ClickHouse.Client.Copy.ClickHouseBulkCopy..ctor(ClickHouseConnection)
   at LinqToDB.Expressions.TypeMapper.<>c.<ReplaceTypes>b__27_0(ReplaceTypesContext context, Expression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.ExpressionExtensions.Transform[TContext](Expression expr, TContext context, Func`3 func)
   at LinqToDB.Expressions.TypeMapper.ReplaceTypes(Expression expression, ReplaceTypesContext ctx)
   at LinqToDB.Expressions.TypeMapper.MapLambdaInternal(LambdaExpression lambda, Boolean mapConvert, Boolean convertResult, Boolean ignoreMissingMembers)
   at LinqToDB.Expressions.TypeMapper.BuildWrapperImpl(LambdaExpression lambda, Boolean wrapResult, Boolean optional, Type returnTypeOverride)
   at LinqToDB.Expressions.TypeMapper.BuildFactoryImpl[T](LambdaExpression lambda, Boolean wrapResult)
   at LinqToDB.Expressions.TypeMapper.BuildWrappedFactory[T,TR](Expression`1 newFunc)
   at LinqToDB.DataProvider.ClickHouse.ClickHouseProviderAdapter.CreateClientAdapter()
   at LinqToDB.DataProvider.ClickHouse.ClickHouseProviderAdapter.GetInstance(ClickHouseProvider provider)
   at LinqToDB.DataProvider.ClickHouse.ClickHouseMappingSchema.ClientMappingSchema..ctor()
   at LinqToDB.DataProvider.ClickHouse.ClickHouseDataProvider.GetMappingSchema(ClickHouseProvider provider)
   at LinqToDB.DataProvider.ClickHouse.ClickHouseDataProvider..ctor(String name, ClickHouseProvider provider)
   at LinqToDB.DataProvider.ClickHouse.ClickHouseClientDataProvider..ctor()
   at System.RuntimeType.CreateInstanceOfT()
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at LinqToDB.DataProvider.ProviderDetectorBase`2.<>c__1`1.<CreateDataProvider>b__1_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at LinqToDB.DataProvider.ClickHouse.ClickHouseProviderDetector.GetDataProvider(ConnectionOptions options, ClickHouseProvider provider, Dialect version)
   at LinqToDB.DataProvider.ProviderDetectorBase`2.CreateOptions(DataOptions options, TVersion dialect, TProvider provider)
   at LinqToDB.DataOptionsExtensions.UseClickHouse(DataOptions options, ClickHouseProvider provider, Func`2 optionSetter)
   at LinqToDB.DataOptionsExtensions.UseClickHouse(DataOptions options, String connectionString, ClickHouseProvider provider, Func`2 optionSetter)
   at DataModels.ClickHouse.ClientHouseDB.GetDataOptions(String configString) in P:\LinqToDBTest\DataModels.cs:line 26
   at DataModels.ClickHouse.ClientHouseDB..ctor() in P:\LinqToDBTest\ClickHouseDB.generated.cs:line 42
   at LinqToDBTest.Program.Main(String[] args) in P:\LinqToDBTest\Program.cs:line 20

```

### Expected Behavior

7.8.2 works just fine.

### Environment

```markdown
- OS: Windows
- Runtime: net8.0
```

**Comment by igor-tkachev** [comment]
7.8.3 works as well.

**Comment by SMAH1** [comment]
I have same issue.
After checking, I noticed that you have removed the **default constructor** of the `ClickHouseBulkCopy` class which takes only **one parameter**.

**Comment by DarkWanderer** [comment]
Thanks for report. Looks like unintended consequence of adding a default-value parameter to constructor - https://github.com/DarkWanderer/ClickHouse.Client/pull/541/files#diff-1d47bdcdc288905072a1548d31e9b8e961d40c9b904d2d947d2885276804a4aaR27

Please try package version 7.9.1

Can you share an example of code where this issue would be reproduced? I'll add it to unit tests

**Comment by MaceWindu** [comment]
@DarkWanderer, I don't think unit test will help with issues like that.

This specific issue caused by the way we consume ADO.NET providers in LinqToDB: all non-standard APIs are mapped using reflection as:
- we cannot just add direct references to many different providers to library
- we cannot tell user to use specific provider version and need to support some sane range of recent versions even if they have API changes including not released versions (if they don't break for us)

E.g. specific to this issue mapping is [here](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/ClickHouse/ClickHouseProviderAdapter.cs#L415)

This approach breaks from time to time (like we have it here) when binary-incompatible (or behavior) API changes occur in provider and in general it is recommended to avoid such changes in non-major versions.

As solution I would recommend to add public API baselines to detect API breaking changes before they released using https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers

**Comment by DarkWanderer** [comment]
The test I was looking for was not about checking the constructors themselves, but rather an integration test which references the library itself and smoke tests a few basic scenarios with downstream libraries - Linq2DB, EFCore.ClickHouse etc. As evidenced by this bug, having this type of test would be beneficial.

Is there a "golden path" with Linq2DB which Ilyou would recommend including into such a test suite?

Thank you for the package suggestion, I had something like this in mind for a while but didn't know it has already been implemented, will definitely take a look

**Comment by MaceWindu** [comment]
Looking at API we use through reflection I would say following code will cover all of it:

```cs
sealed class TestTable
{
	public int Id { get; set; }

	// test provider-specific type mapping
	public ClickHouseDecimal CustomType { get; set; }
}

// test
await using var db = new DataConnection(new DataOptions().UseClickHouse(ClickHouseProvider.ClickHouseClient, connectionString));

// cannot use temp table as we need to test WithoutSession option
var tb = await db.CreateTableAsync<TestTable>();

try
{
	var options = new BulkCopyOptions()
	{
		MaxBatchSize = 10,
		MaxDegreeOfParallelism = 1,
		WithoutSession = true
	};

	await tb.BulkCopyAsync(options, [new TestTable() { Id = 1, CustomType = new ClickHouseDecimal(123) }]);

	// test ClickHouseDecimal ToString call mapping
	db.InlineParameters = true;
	await tb.Where(r => r.CustomType == new ClickHouseDecimal(123)).ToArrayAsync();
}
finally
{
	await tb.DropAsync();
}
```

**Comment by MaceWindu** [comment]
I've checked our mappings and there are some more APIs used. Will update example in an hour

**Comment by MaceWindu** [comment]
Added additional code to test remaining apis and comments to specify which APIs covered:

```cs
sealed class TestTable
{
	public int Id { get; set; }

	// test provider-specific type mapping
	public ClickHouseDecimal Decimal { get; set; }

	// test custom data reader Get* methods:

	// ClickHouseDataReader::GetIPAddress(int)
	public IPAddress? IPAddress { get; set; }
	// ClickHouseDataReader::GetSByte(int)
	public sbyte SByte { get; set; }
	// ClickHouseDataReader::GetUInt16(int)
	public ushort UInt16 { get; set; }
	// ClickHouseDataReader::GetUInt32(int)
	public uint UInt32 { get; set; }
	// ClickHouseDataReader::GetUInt64(int)
	public ulong UInt64 { get; set; }
	// ClickHouseDataReader::GetBigInteger(int)
	public BigInteger BigInteger { get; set; }

	public static TestTable[] TestData =
	[
		new TestTable()
		{
			Id = 1,
			Decimal = new ClickHouseDecimal(12.3M),
			IPAddress = IPAddress.Parse("1::"),
			SByte = -123,
			UInt16 = ushort.MaxValue,
			UInt32 = uint.MaxValue,
			UInt64 = ulong.MaxValue,
			BigInteger = BigInteger.Parse("567846734868672348679623672346")
		}
	];
}

// Covers: ClickHouseConnection::..ctor(string)
await using var db = new DataConnection(new DataOptions().UseClickHouse(ClickHouseProvider.ClickHouseClient, connectionString));

// cannot use temp table as we need to test WithoutSession option, incompatible with session tables
var tb = await db.CreateTableAsync<TestTable>();

try
{
	var options = new BulkCopyOptions()
	{
		// Covers: ClickHouseBulkCopy::BatchSize
		MaxBatchSize = 10,
		// Covers: ClickHouseBulkCopy::MaxDegreeOfParallelism
		MaxDegreeOfParallelism = 1,
		// Covers:
		// ClickHouseConnectionStringBuilder::.ctor(string)
		// ClickHouseConnectionStringBuilder::UseSession
		// ClickHouseConnectionStringBuilder::ToString
		WithoutSession = true
	};

	// Covers:
	// ClickHouseBulkCopy::.ctor(ClickHouseConnection)
	// ClickHouseBulkCopy::Dispose()
	// ClickHouseBulkCopy::DestinationTableName
	// ClickHouseBulkCopy::RowsWritten
	// ClickHouseBulkCopy::InitAsync
	// ClickHouseBulkCopy::ColumnNames
	await tb.BulkCopyAsync(options, TestTable.TestData);

	db.InlineParameters = true;
	// Covers:
	// ClickHouseDecimal::ToString(IFormatProvider)
	var record = await tb.Where(r => r.Decimal == new ClickHouseDecimal(12.3M)).SingleAsync();

	// optional assert could be added
}
finally
{
	await tb.DropAsync();
}
```

**Comment by DarkWanderer** [comment]
Thank you very much. I've added a separate test suite which includes this scenario, so hopefully we won't meet this failure mode again. If anyone is aware of other libraries utilizing reflection on `ClickHouse.Client` which we can add here, let me know

TODO:

- [ ] add [Microsoft.CodeAnalysis.PublicApiAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers)

**Comment by DarkWanderer** [comment]
Added public API definitions in #565

Thanks for suggestion @MaceWindu
